### ISSUE TITLE
MacOS executable is broken

### ISSUE THREAD

**Issue by fsoupimenta** [GraphFilter/GraphFilter#212]
Creating a new release, it was noticed that the MacOS executable is generated, but when running the program, it opens multiple tabs.

It would be convenient to carry out the same process with a previous version, for a better visualization of the problem.

**Comment by rosaigor138** [comment]
### In the proccess to discover what is the error ocorring. I tried to run de exe by the command terminal, to see if i get some traceback of error. But nothing new appears, besides that error.

- >```bjc[2879]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffabb783c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10659ff50). One of the two will be used. Which one is undefined.```
>
#### That way to verify if this happen in other versions i download the 2.2.0 version of the Graph Filter and tried the same process, and it works well.

- And i notice the command responsible to generate the executable sometimes generate the command exec and others the command exec and the .app.

- That is the exec I run in the terminal,

![execGraphFilter](https://user-images.githubusercontent.com/93498324/209195397-ae0e4463-59bd-4dd3-964a-f071630bf567.jpeg)


#### To make the 2.2.0 requirements.txt installation I needed to change some of the libraries version, I tried to mantain the closest versions possible to the original 2.2.0. To verify I will change the 2.3.0 requirements to the same version as the 2.2.0, to see if it is one of the libraries, because the error seeing above is something envolving Apple native libraries and downloaded ones (Something like a override). You can see more [here](https://developer.apple.com/forums/thread/115591).

**Comment by LBeghini** [comment]
Looking at the error, I found an [answer in StackOverflow](https://stackoverflow.com/a/63892045/13160199). It is worth to take a look.

**Comment by fsoupimenta** [comment]
Before the new year i found this [issue](https://github.com/pyinstaller/pyinstaller/issues/4067). Maybe can be a way to solve the problem.
I also suspect that the implementation of parallelism might be involved with the problem, it's worth investigating.
