### ISSUE TITLE
Find common invariants in loaded graphs

### ISSUE THREAD

**Issue by Viech** [GraphFilter/GraphFilter#331]
When loading a collection of graphs from the filesystem, it would be great if one could check for all supported invariants that the graphs have in common. This would help with identifying properties of graphs that were generated externally.

**Comment by atilaajones** [comment]
Hi @Viech.
Do you want to load a list of graphs in .g6 and know which graphs have a common value for a given invariant? If yes, this can be done by exporting all files to a spreadsheet (File > Export all), this function exports the graphs and the selected invariants on the same spreadsheet. So in Excel you can use filters to identify graphs with the same invariant result.

Is this the case?

If you mean something different, could you explain your demand so we can better understand it?

**Comment by Viech** [comment]
> Do you want to load a list of graphs in .g6 and know which graphs have a common value for a given invariant?

I'm particularly interested in invariants shared by _all_ loaded graphs.

Say I have a function that generates graphs from some class (e.g. graphs having some complicated property X) and I am looking to learn additional properties of this class.

> If yes, this can be done by exporting all files to a spreadsheet (File > Export all), this function exports the graphs and the selected invariants on the same spreadsheet. So in Excel you can use filters to identify graphs with the same invariant result.

This is good to know, though I still find that this would be a good fit for the software itself. It was among the things that I expected it would be able to do when I installed it.

**Comment by atilaajones** [comment]
Yes, I understood. You are looking for invariants that are based on comparisons between graphs, for example cospectral graphs.In this case our software does not support it yet.  
 
We are developing a new version that will come with several new features very soon, but we will take note of your demand for a future release. For now, EXCEL helps a lot, because there you can use spreadsheet filters to compare invariants of several graphs at the same time.
