### ISSUE TITLE
Spectrum of distance matrix of a split complete graph

### ISSUE THREAD

**Issue by CybeleVinagre** [GraphFilter/GraphFilter#365]
Dear all
GraphFilter gives a null eigenvalue for the distance matrix of the split complete graph obtained from the join of
complement graph of K_2 with K_7. It can be proved that D-matrix is invertible for this graph.

**Comment by atilaajones** [comment]
This could be some mistake, because when checking the spectum of the distance matrix of the `comp(K_2) join K7` really has no zero eigenvalue. See image below.
![image](https://github.com/GraphFilter/GraphFilter/assets/41593241/7dbdb9ac-feab-4c9a-8c09-7d859c43b666)

If the error is detected again, please report it to us.
